version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: traffboard-db
    environment:
      POSTGRES_DB: traffboard
      POSTGRES_USER: traffboard_user
      POSTGRES_PASSWORD: traffboard_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U traffboard_user -d traffboard"]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:latest
    container_name: traffboard-adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local
